import type { NewPlan } from "../schema/plans.js";
import type { PlanFeatures } from "@workspace/shared";

// Origen: precios sin cambio — fórmula original (mensual = anual÷10, 3cuotas = anual×1.10, num_cuotas=3)
function preciosOrigen(anual: number): {
  precio_mensual_cop: number;
  precio_3cuotas_total_cop: number;
  num_cuotas: number;
} {
  if (anual === 0) return { precio_mensual_cop: 0, precio_3cuotas_total_cop: 0, num_cuotas: 3 };
  return {
    precio_mensual_cop: Math.round(anual / 10),
    precio_3cuotas_total_cop: Math.round(anual * 1.10),
    num_cuotas: 3,
  };
}

// ── Precios 2026 (PROMOCIONALES) — vigentes para cobro ─────────────────────
// En 2027 los clientes que renueven pasan al precio_regular_*
// Para actualizar a regular: cambiar precio_anual_cop y precio_mensual_cop a los valores de precio_regular_*

// ERP
const PROMO_ERP = {
  semilla:  { anual: 590_000, mensual: 55_000, cuotasTotal: 626_000, numCuotas: 2, regular_anual: 730_000, regular_mensual: 73_000 },
  raiz:     { anual: 790_000, mensual: 74_000, cuotasTotal: 838_000, numCuotas: 3, regular_anual: 990_000, regular_mensual: 99_000 },
  brote:    { anual: 1_190_000, mensual: 110_000, cuotasTotal: 1_262_000, numCuotas: 4, regular_anual: 1_450_000, regular_mensual: 145_000 },
  cosecha:  { anual: 1_590_000, mensual: 149_000, cuotasTotal: 1_686_000, numCuotas: 4, regular_anual: 1_990_000, regular_mensual: 199_000 },
} as const;

// POS
const PROMO_POS = {
  punto:       { anual: 360_000, mensual: 34_000, cuotasTotal: 382_000, numCuotas: 2, regular_anual: 450_000, regular_mensual: 45_000 },
  punto_plus:  { anual: 630_000, mensual: 59_000, cuotasTotal: 668_000, numCuotas: 2, regular_anual: 790_000, regular_mensual: 79_000 },
} as const;

const noFeatures: PlanFeatures = {
  pos:                    false,
  pos_multi_caja:         false,
  inventario:             false,
  facturacion_ilimitada:  false,
  facturacion_recurrente: false,
  reportes_comparativos:  false,
  centros_costos:         false,
  multi_sede:             false,
  ensamble:               false,
  cartera_avanzada:       false,
  cotizaciones:           false,
  cotizacion_a_factura:   false,
  oportunidades_crm:      false,
  pipeline_comercial:     false,
  gastos:                 false,
  cuentas_por_pagar:      false,
  programacion_pagos:     false,
  flujo_caja:             false,
  ia_asistente:           false,
  agenda_servicios:       false,
  conciliacion_bancaria:  false,
};

// Features compartidas por todos los planes Origen
const origenFeatures: PlanFeatures = { ...noFeatures };

export const PLAN_SEEDS: NewPlan[] = [
  // ── Origen: facturación electrónica pura (sin cambio de precios) ─────────
  {
    slug: "origen",
    nombre: "Origen 10",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 10,
    max_ia_docs_mes: 0,
    document_limit: 10,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 0,
    ...preciosOrigen(0),
  },
  {
    slug: "origen_24",
    nombre: "Origen 24",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 24,
    max_ia_docs_mes: 0,
    document_limit: 24,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 99_900,
    ...preciosOrigen(99_900),
  },
  {
    slug: "origen_60",
    nombre: "Origen 60",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 60,
    max_ia_docs_mes: 0,
    document_limit: 60,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 169_900,
    ...preciosOrigen(169_900),
  },
  {
    slug: "origen_120",
    nombre: "Origen 120",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 120,
    max_ia_docs_mes: 0,
    document_limit: 120,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 249_900,
    ...preciosOrigen(249_900),
  },
  {
    slug: "origen_300",
    nombre: "Origen 300",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 300,
    max_ia_docs_mes: 0,
    document_limit: 300,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 329_900,
    ...preciosOrigen(329_900),
  },

  // ── ERP: escalera principal ───────────────────────────────────────────────
  {
    slug: "semilla",
    nombre: "Semilla",
    product: "erp",
    max_usuarios: 3,
    max_bodegas: 2,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 30,
    accounting_level: 1,   // libro diario + mayor
    features: {
      ...noFeatures,
      inventario:            true,
      facturacion_ilimitada: true,
      cotizaciones:          true,
      cotizacion_a_factura:  true,
      cartera_avanzada:      true,
      gastos:                true,
      cuentas_por_pagar:     true,
      ia_asistente:          true,
      conciliacion_bancaria: true,
    },
    precio_anual_cop:           PROMO_ERP.semilla.anual,
    precio_mensual_cop:         PROMO_ERP.semilla.mensual,
    precio_3cuotas_total_cop:   PROMO_ERP.semilla.cuotasTotal,
    num_cuotas:                 PROMO_ERP.semilla.numCuotas,
    precio_regular_anual_cop:   PROMO_ERP.semilla.regular_anual,
    precio_regular_mensual_cop: PROMO_ERP.semilla.regular_mensual,
  },
  {
    slug: "raiz",
    nombre: "Raíz",
    product: "erp",
    max_usuarios: 5,
    max_bodegas: 3,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 100,
    accounting_level: 2,   // + balance general + estado de resultados
    features: {
      ...noFeatures,
      inventario:            true,
      facturacion_ilimitada: true,
      cotizaciones:          true,
      cotizacion_a_factura:  true,
      cartera_avanzada:      true,
      gastos:                true,
      cuentas_por_pagar:     true,
      programacion_pagos:    true,
      ensamble:              true,
      ia_asistente:          true,
      conciliacion_bancaria: true,
    },
    precio_anual_cop:           PROMO_ERP.raiz.anual,
    precio_mensual_cop:         PROMO_ERP.raiz.mensual,
    precio_3cuotas_total_cop:   PROMO_ERP.raiz.cuotasTotal,
    num_cuotas:                 PROMO_ERP.raiz.numCuotas,
    precio_regular_anual_cop:   PROMO_ERP.raiz.regular_anual,
    precio_regular_mensual_cop: PROMO_ERP.raiz.regular_mensual,
  },
  {
    slug: "brote",
    nombre: "Brote",
    product: "erp",
    max_usuarios: 10,
    max_bodegas: 5,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 300,
    accounting_level: 3,   // + reportes comparativos
    features: {
      ...noFeatures,
      inventario:             true,
      facturacion_ilimitada:  true,
      facturacion_recurrente: true,
      reportes_comparativos:  true,
      cotizaciones:           true,
      cotizacion_a_factura:   true,
      oportunidades_crm:      true,
      cartera_avanzada:       true,
      gastos:                 true,
      cuentas_por_pagar:      true,
      programacion_pagos:     true,
      ensamble:               true,
      ia_asistente:           true,
      conciliacion_bancaria:  true,
    },
    precio_anual_cop:           PROMO_ERP.brote.anual,
    precio_mensual_cop:         PROMO_ERP.brote.mensual,
    precio_3cuotas_total_cop:   PROMO_ERP.brote.cuotasTotal,
    num_cuotas:                 PROMO_ERP.brote.numCuotas,
    precio_regular_anual_cop:   PROMO_ERP.brote.regular_anual,
    precio_regular_mensual_cop: PROMO_ERP.brote.regular_mensual,
  },
  {
    slug: "cosecha",
    nombre: "Cosecha",
    product: "erp",
    max_usuarios: null,
    max_bodegas: null,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: null,
    accounting_level: 4,   // + centros de costos
    features: {
      inventario:             true,
      facturacion_ilimitada:  true,
      facturacion_recurrente: true,
      reportes_comparativos:  true,
      centros_costos:         true,
      multi_sede:             true,
      ensamble:               true,
      cartera_avanzada:       true,
      cotizaciones:           true,
      cotizacion_a_factura:   true,
      oportunidades_crm:      true,
      pipeline_comercial:     true,
      gastos:                 true,
      cuentas_por_pagar:      true,
      programacion_pagos:     true,
      flujo_caja:             true,
      ia_asistente:           true,
      agenda_servicios:       false,
      conciliacion_bancaria:  true,
      pos:                    false,
      pos_multi_caja:         false,
    },
    precio_anual_cop:           PROMO_ERP.cosecha.anual,
    precio_mensual_cop:         PROMO_ERP.cosecha.mensual,
    precio_3cuotas_total_cop:   PROMO_ERP.cosecha.cuotasTotal,
    num_cuotas:                 PROMO_ERP.cosecha.numCuotas,
    precio_regular_anual_cop:   PROMO_ERP.cosecha.regular_anual,
    precio_regular_mensual_cop: PROMO_ERP.cosecha.regular_mensual,
  },

  // ── Punto de venta (POS) ─────────────────────────────────────────────────
  {
    slug: "punto",
    nombre: "Punto",
    product: "pos",
    max_usuarios: 2,
    max_bodegas: 1,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: {
      ...noFeatures,
      inventario: true,
      gastos:     true,
      pos:        true,
    },
    precio_anual_cop:           PROMO_POS.punto.anual,
    precio_mensual_cop:         PROMO_POS.punto.mensual,
    precio_3cuotas_total_cop:   PROMO_POS.punto.cuotasTotal,
    num_cuotas:                 PROMO_POS.punto.numCuotas,
    precio_regular_anual_cop:   PROMO_POS.punto.regular_anual,
    precio_regular_mensual_cop: PROMO_POS.punto.regular_mensual,
  },
  {
    slug: "punto_plus",
    nombre: "Punto Plus",
    product: "pos",
    max_usuarios: null,
    max_bodegas: 3,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 0,
    accounting_level: 1,
    features: {
      ...noFeatures,
      inventario:            true,
      gastos:                true,
      cuentas_por_pagar:     true,
      conciliacion_bancaria: true,
      pos:                   true,
      pos_multi_caja:        true,
      agenda_servicios:      true,
    },
    precio_anual_cop:           PROMO_POS.punto_plus.anual,
    precio_mensual_cop:         PROMO_POS.punto_plus.mensual,
    precio_3cuotas_total_cop:   PROMO_POS.punto_plus.cuotasTotal,
    num_cuotas:                 PROMO_POS.punto_plus.numCuotas,
    precio_regular_anual_cop:   PROMO_POS.punto_plus.regular_anual,
    precio_regular_mensual_cop: PROMO_POS.punto_plus.regular_mensual,
  },
];
