import type { NewPlan } from "../schema/plans.js";
import type { PlanFeatures } from "@workspace/shared";

// Calcula precios de modalidades (spec: mensual = anual÷10, 3cuotas = anual×1.10)
function precios(anual: number): { precio_mensual_cop: number; precio_3cuotas_total_cop: number } {
  if (anual === 0) return { precio_mensual_cop: 0, precio_3cuotas_total_cop: 0 };
  const mensual = Math.round(anual / 10);
  const tresCuotas = Math.round(anual * 1.10);
  return { precio_mensual_cop: mensual, precio_3cuotas_total_cop: tresCuotas };
}

const noFeatures: PlanFeatures = {
  pos:                    false,
  pos_multi_caja:         false,
  inventario:             false,
  facturacion_ilimitada:  false,
  facturacion_recurrente: false,
  reportes_comparativos:  false,
  centros_costos:         false,
  multi_sede:             false,
  ensamble:               false,
  cartera_avanzada:       false,
  cotizaciones:           false,
  cotizacion_a_factura:   false,
  oportunidades_crm:      false,
  pipeline_comercial:     false,
  gastos:                 false,
  cuentas_por_pagar:      false,
  programacion_pagos:     false,
  flujo_caja:             false,
  ia_asistente:           false,
  agenda_servicios:       false,
  conciliacion_bancaria:  false,
};

// Features compartidas por todos los planes Origen
const origenFeatures: PlanFeatures = { ...noFeatures };

export const PLAN_SEEDS: NewPlan[] = [
  // ── Origen: facturación electrónica pura ─────────────────────────────────
  {
    slug: "origen",
    nombre: "Origen 10",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 10,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 0,
    ...precios(0),
  },
  {
    slug: "origen_24",
    nombre: "Origen 24",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 24,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 99_900,
    ...precios(99_900),
  },
  {
    slug: "origen_60",
    nombre: "Origen 60",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 60,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 169_900,
    ...precios(169_900),
  },
  {
    slug: "origen_120",
    nombre: "Origen 120",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 120,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 249_900,
    ...precios(249_900),
  },
  {
    slug: "origen_300",
    nombre: "Origen 300",
    product: "origen",
    max_usuarios: 1,
    max_bodegas: 0,
    max_facturas_mes: null,
    max_facturas_ano: 300,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: { ...origenFeatures },
    precio_anual_cop: 329_900,
    ...precios(329_900),
  },

  // ── ERP: escalera principal ───────────────────────────────────────────────
  {
    slug: "semilla",
    nombre: "Semilla",
    product: "erp",
    max_usuarios: 3,
    max_bodegas: 2,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 30,
    accounting_level: 1,   // libro diario + mayor
    features: {
      ...noFeatures,
      inventario:            true,
      facturacion_ilimitada: true,
      cotizaciones:          true,
      cotizacion_a_factura:  true,
      cartera_avanzada:      true,
      gastos:                true,
      cuentas_por_pagar:     true,
      ia_asistente:          true,
      conciliacion_bancaria: true,
    },
    precio_anual_cop: 730_000,
    ...precios(730_000),
  },
  {
    slug: "raiz",
    nombre: "Raíz",
    product: "erp",
    max_usuarios: 5,
    max_bodegas: 3,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 100,
    accounting_level: 2,   // + balance general + estado de resultados
    features: {
      ...noFeatures,
      inventario:            true,
      facturacion_ilimitada: true,
      cotizaciones:          true,
      cotizacion_a_factura:  true,
      cartera_avanzada:      true,
      gastos:                true,
      cuentas_por_pagar:     true,
      programacion_pagos:    true,
      ensamble:              true,
      ia_asistente:          true,
      conciliacion_bancaria: true,
    },
    precio_anual_cop: 990_000,
    ...precios(990_000),
  },
  {
    slug: "brote",
    nombre: "Brote",
    product: "erp",
    max_usuarios: 10,
    max_bodegas: 5,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 300,
    accounting_level: 3,   // + reportes comparativos
    features: {
      ...noFeatures,
      inventario:             true,
      facturacion_ilimitada:  true,
      facturacion_recurrente: true,
      reportes_comparativos:  true,
      cotizaciones:           true,
      cotizacion_a_factura:   true,
      oportunidades_crm:      true,
      cartera_avanzada:       true,
      gastos:                 true,
      cuentas_por_pagar:      true,
      programacion_pagos:     true,
      ensamble:               true,
      ia_asistente:           true,
      conciliacion_bancaria:  true,
    },
    precio_anual_cop: 1_450_000,
    ...precios(1_450_000),
  },
  {
    slug: "cosecha",
    nombre: "Cosecha",
    product: "erp",
    max_usuarios: null,
    max_bodegas: null,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: null,
    accounting_level: 4,   // + centros de costos
    features: {
      inventario:             true,
      facturacion_ilimitada:  true,
      facturacion_recurrente: true,
      reportes_comparativos:  true,
      centros_costos:         true,
      multi_sede:             true,
      ensamble:               true,
      cartera_avanzada:       true,
      cotizaciones:           true,
      cotizacion_a_factura:   true,
      oportunidades_crm:      true,
      pipeline_comercial:     true,
      gastos:                 true,
      cuentas_por_pagar:      true,
      programacion_pagos:     true,
      flujo_caja:             true,
      ia_asistente:           true,
      agenda_servicios:       false,
      conciliacion_bancaria:  true,
      pos:                    false,
      pos_multi_caja:         false,
    },
    precio_anual_cop: 1_990_000,
    ...precios(1_990_000),
  },

  // ── Punto de venta (POS) ─────────────────────────────────────────────────
  {
    slug: "punto",
    nombre: "Punto",
    product: "pos",
    max_usuarios: 2,
    max_bodegas: 1,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 0,
    accounting_level: 0,
    features: {
      ...noFeatures,
      inventario: true,
      gastos:     true,
      pos:        true,
    },
    precio_anual_cop: 450_000,
    ...precios(450_000),
  },
  {
    slug: "punto_plus",
    nombre: "Punto Plus",
    product: "pos",
    max_usuarios: null,
    max_bodegas: 3,
    max_facturas_mes: null,
    max_facturas_ano: null,
    max_ia_docs_mes: 0,
    accounting_level: 1,
    features: {
      ...noFeatures,
      inventario:        true,
      gastos:                true,
      cuentas_por_pagar:     true,
      conciliacion_bancaria: true,
      pos:                   true,
      pos_multi_caja:        true,
      agenda_servicios:      true,
    },
    precio_anual_cop: 790_000,
    ...precios(790_000),
  },
];
