import { useCallback, useEffect, useMemo, useState } from "react";
import { Copy, FileText, Plus, Send } from "lucide-react";
import { apiFetch, cop } from "../lib/api";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";

type Account = { id: string; nombre_comercial: string };
type Opportunity = { id: string; account_id: string; nombre: string };
type Plan = { id: string; nombre: string; product: string; precio_anual_cop: number; precio_mensual_cop: number | null };
type Quote = { id: string; quote_number: string; account_id: string; opportunity_id: string | null; total: string; status: string; valid_until: string | null; public_token: string; view_count: number };

const statusName: Record<string, string> = { draft: "Borrador", sent: "Enviada", viewed: "Vista", accepted: "Aceptada", rejected: "Rechazada", expired: "Vencida", payment_pending: "Pago pendiente", paid: "Pagada", cancelled: "Cancelada" };

export default function FundadorQuotes() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [quotes, setQuotes] = useState<Quote[]>([]);
  const [accountId, setAccountId] = useState(""); const [opportunityId, setOpportunityId] = useState(""); const [planId, setPlanId] = useState(""); const [quantity, setQuantity] = useState(1); const [validUntil, setValidUntil] = useState(""); const [showForm, setShowForm] = useState(false); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const selectedPlan = plans.find((p) => p.id === planId);
  const visibleOpportunities = useMemo(() => opportunities.filter((o) => o.account_id === accountId), [accountId, opportunities]);
  const load = useCallback(async () => { try { const [a, o, p, q] = await Promise.all([apiFetch<Account[]>("/api/fundador/sales/accounts"), apiFetch<Opportunity[]>("/api/fundador/sales/opportunities"), apiFetch<Plan[]>("/api/fundador/sales/catalog"), apiFetch<Quote[]>("/api/fundador/sales/quotes")]); setAccounts(a); setOpportunities(o); setPlans(p); setQuotes(q); } catch (err) { setError(err instanceof Error ? err.message : "No se pudieron cargar las cotizaciones."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function createQuote() { if (!accountId || !selectedPlan) return; setSaving(true); setError(null); try { await apiFetch("/api/fundador/sales/quotes", { method: "POST", body: JSON.stringify({ account_id: accountId, opportunity_id: opportunityId || undefined, valid_until: validUntil || undefined, items: [{ plan_id: selectedPlan.id, description: `${selectedPlan.nombre} (${selectedPlan.product})`, quantity, unit_price: selectedPlan.precio_anual_cop, billing_period: "annual" }] }) }); setShowForm(false); setPlanId(""); setQuantity(1); await load(); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo crear la cotización."); } finally { setSaving(false); } }
  async function send(quote: Quote) { try { await apiFetch(`/api/fundador/sales/quotes/${quote.id}/status`, { method: "PATCH", body: JSON.stringify({ status: "sent" }) }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo enviar la cotización."); } }
  async function copyLink(quote: Quote) { await navigator.clipboard.writeText(`${window.location.origin}/propuesta/${quote.public_token}`); }
  return <div className="p-6 space-y-6 max-w-6xl mx-auto"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold tracking-widest text-slate-400 uppercase">Revenue Operations</p><h1 className="text-2xl font-bold">Cotizaciones Doravia</h1><p className="text-sm text-slate-500">Propuestas comerciales para prospectos, separadas de las cotizaciones de cada cliente.</p></div><Button onClick={() => setShowForm(!showForm)}><Plus className="h-4 w-4" />Nueva cotización</Button></div>{error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {showForm && <Card><CardContent className="p-5 grid gap-4 md:grid-cols-2"><div><Label>Cuenta</Label><select className="w-full rounded-md border p-2" value={accountId} onChange={(e) => { setAccountId(e.target.value); setOpportunityId(""); }}><option value="">Selecciona</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.nombre_comercial}</option>)}</select></div><div><Label>Oportunidad (opcional)</Label><select className="w-full rounded-md border p-2" value={opportunityId} onChange={(e) => setOpportunityId(e.target.value)} disabled={!accountId}><option value="">Sin vincular</option>{visibleOpportunities.map((o) => <option key={o.id} value={o.id}>{o.nombre}</option>)}</select></div><div><Label>Plan del catálogo</Label><select className="w-full rounded-md border p-2" value={planId} onChange={(e) => setPlanId(e.target.value)}><option value="">Selecciona</option>{plans.map((p) => <option key={p.id} value={p.id}>{p.nombre} · {cop(p.precio_anual_cop)}/año</option>)}</select></div><div><Label>Cantidad</Label><Input type="number" min="1" value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} /></div><div><Label>Vigencia</Label><Input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} /></div><div className="flex items-end"><Button onClick={() => void createQuote()} disabled={!accountId || !selectedPlan || saving}>{saving ? "Creando..." : "Crear borrador"}</Button></div></CardContent></Card>}
    <Card><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-3">Número</th><th className="p-3">Estado</th><th className="p-3">Total</th><th className="p-3">Vigencia</th><th className="p-3">Aperturas</th><th className="p-3">Acciones</th></tr></thead><tbody>{quotes.map((q) => <tr key={q.id} className="border-t"><td className="p-3 font-medium">{q.quote_number}</td><td className="p-3"><Badge variant={q.status === "paid" || q.status === "accepted" ? "green" : q.status === "draft" ? "gray" : "blue"}>{statusName[q.status] ?? q.status}</Badge></td><td className="p-3">{cop(q.total)}</td><td className="p-3">{q.valid_until ?? "Sin fecha"}</td><td className="p-3">{q.view_count}</td><td className="p-3 flex gap-2">{q.status === "draft" && <Button size="sm" onClick={() => void send(q)}><Send className="h-3 w-3" />Marcar enviada</Button>}<Button size="sm" variant="secondary" onClick={() => void copyLink(q)} title="Copiar enlace público"><Copy className="h-3 w-3" />Link</Button></td></tr>)}{!quotes.length && <tr><td colSpan={6} className="p-8 text-center text-slate-400"><FileText className="h-5 w-5 inline mr-2" />Aún no hay cotizaciones comerciales.</td></tr>}</tbody></table></CardContent></Card></div>;
}
